In [ ]:
import numpy as np

In [ ]:
def sigmoid(sum):
  return 1/(1+np.exp(-sum))

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.exp(2)

7.38905609893065

In [ ]:
np.exp(0)

1.0

In [ ]:
sigmoid(-25)

1.3887943864771144e-11

In [ ]:
inputs=np.array([[0,0],[0,1],[1,0],[1,1]])

In [ ]:
inputs.shape

(4, 2)

In [ ]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
outputs=np.array([[0],[1],[1],[0]])

In [ ]:
outputs.shape

(4, 1)

In [ ]:
outputs

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
weights0=np.array([[-0.424,-0.740,-0.961],[0.358,-0.577,-0.469]])

In [ ]:
weights0

array([[-0.424, -0.74 , -0.961],
       [ 0.358, -0.577, -0.469]])

In [ ]:
weights1=np.array([[-0.017],[-0.893],[0.148]])

In [ ]:
epochs=100
learning_rate=0.3

In [ ]:
input_layer=inputs
input_layer

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
sum_synapse0=np.dot(input_layer,weights0)
sum_synapse0

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.358, -0.577, -0.469],
       [-0.424, -0.74 , -0.961],
       [-0.066, -1.317, -1.43 ]])

In [ ]:
hidden_layer=sigmoid(sum_synapse0)
hidden_layer

array([[0.5       , 0.5       , 0.5       ],
       [0.5885562 , 0.35962319, 0.38485296],
       [0.39555998, 0.32300414, 0.27667802],
       [0.48350599, 0.21131785, 0.19309868]])

In [ ]:
weights1

array([[-0.017],
       [-0.893],
       [ 0.148]])

In [ ]:
sum_synapse1=np.dot(hidden_layer,weights1)
sum_synapse1

array([[-0.381     ],
       [-0.27419072],
       [-0.25421887],
       [-0.16834784]])

In [ ]:
output_layer=sigmoid(sum_synapse1)
output_layer

array([[0.40588573],
       [0.43187857],
       [0.43678536],
       [0.45801216]])

In [ ]:
error_output_layer=outputs-output_layer
error_output_layer

array([[-0.40588573],
       [ 0.56812143],
       [ 0.56321464],
       [-0.45801216]])

In [ ]:
average=np.mean(abs(error_output_layer))
average

0.49880848923713045

In [ ]:
def sigmoid_derivative(sigmoid):
  return sigmoid * (1-sigmoid)

In [ ]:
s=sigmoid(0.5)
s

0.6224593312018546

In [ ]:
d=sigmoid_derivative(s)
d

0.2350037122015945

In [ ]:
sigmoid_derivative(0.405)

0.240975

In [ ]:
sigmoid_derivative(0.589)

0.24207900000000002

In [ ]:
output_layer

array([[0.40588573],
       [0.43187857],
       [0.43678536],
       [0.45801216]])

In [ ]:
derivative_output=sigmoid_derivative(output_layer)
derivative_output

array([[0.2411425 ],
       [0.24535947],
       [0.24600391],
       [0.24823702]])

In [ ]:
error_output_layer

array([[-0.40588573],
       [ 0.56812143],
       [ 0.56321464],
       [-0.45801216]])

In [ ]:
delta_output=error_output_layer * derivative_output
delta_output

array([[-0.0978763 ],
       [ 0.13939397],
       [ 0.138553  ],
       [-0.11369557]])